# Generated by Django 5.1.8 on 2025-04-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_blog", "0002_blogcategory_articlepage_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogcategory",
            name="description",
        ),
    ]
