# Generated by Django 5.1.8 on 2025-04-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_blog", "0003_remove_blogcategory_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
    ]
