# Generated by Django 5.1.8 on 2025-04-28 12:25

import wagtailmarkdown.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_blog", "0004_alter_blogcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
