# Generated by Django 5.1.8 on 2025-04-28 12:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_blog", "0005_alter_blogpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="markdown_input",
            field=models.TextField(
                blank=True, help_text="Enter Markdown content here (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
